### ISSUE TITLE
Throw errors earlier

### ISSUE THREAD

**Issue by bas080** [M-erb/dotenv-cast#1]
This package almost scratched my itch. The following would make me use it.

- Throw when the cast did not result in the type that was requested.
- Throw when the variable is undefined/null and no default was defined.

I think it's a good idea to be strict with environment variables to improve the developer experience; as it gives feedback faster when the application is configured in a way that was not accounted for.

**Comment by M-erb** [comment]
Hey @bas080 I apologize I didnt see this till now. I do most of my work on gitlab and didnt catch this. 

These are great suggestions and I will get on them thank you!

**Comment by M-erb** [comment]
[c17b788](https://github.com/M-erb/dotenv-cast/commit/c17b788652a4bd0c23e9d507c8da32604d77899b)

Added:

- Throw when cast does not match method used
- Throw when `.env` variable is blank (aka returns as an empty string) and no default is provided
- Throw when default does not match method used if provided (regardless if actually used or not)
- Add `number` type that accepts both integer and float
- JSON strict to only accept variables that parse to a JS object(instead of anything that `JSON.parse()` accepts)


If there are any more ideas or bugs found, feel free to open up another issue. Thank you!
